common:
  units:
    g: g
    ml: ml
    pieces: pieces

components:
  selectModal:
    title: 'Add/remove items'
  nutrientsChart:
    table:
      calories: Calories
      carbs: Carbs
      protein: Protein
      fat: Fat
    legend:
      carbs: Carbs (g)
      protein: Protein (g)
      fat: Fat (g)
  foodModal:
    title:
      new: New food
      edit: Edit food
      view: View food
    form:
      name: Name
      description: Description
      calories: Calories
      carbs: Carbs (g)
      protein: Protein (g)
      fat: Fat (g)
      serving:
        unit: Serving unit
        value: Serving value
    errors:
      name:
        required: Name is required
      server:
        unknown: Unknown error occurred
  
  dietTable:
    search: Search
    noData: No items available
    noResults: No items found
    loading: Loading items...
    itemsPerPage: Per page
    itemsPerPageAll: All
    name: Name
    amount: Amount
    serving: Serving
    type: Type
    calories: Calories
    carbs: Carbs (g)
    protein: Protein (g)
    fat: Fat (g)

views:
  health:
    title: Health

  diet:
    title: Diet
    search: Search
    newButton: Create food

  exercise:
    title: Exercise

  calculator:
    title: Calculator
    search: Search
    changeItems: Add/remove items
    selectModal:
      title: Add/remove items
