title: Health

common:
  units:
    g: g
    ml: ml
    calories: cal
    percent: '%'
    pieces: piece | pieces
    plates: plate | plates
    serving: serving
    mug: mug | mugs
    cup: cup | cups
    teaspoon: teaspoon | teaspoons

components:
  selectModal:
    title: 'Add/remove items'

  nutrientSummaryChart:
    table:
      calories: Calories
      carbs: Carbs
      protein: Protein
      fat: Fat
    legend:
      calories: Calories (cal)
      carbs: Carbs (g)
      protein: Protein (g)
      fat: Fat (g)
  healthTrendChart:
    legend:
      labels:
        calories: Calories (cal)
        carbs: Carbs (g)
        protein: Protein (g)
        fat: Fat (g)
      days:
        1: '{0}, Mo'
        2: '{0}, Tu'
        3: '{0}, We'
        4: '{0}, Th'
        5: '{0}, Fr'
        6: '{0}, Sa'
        0: '{0}, Su'


  dietTable:
    search: Search
    noData: No items available
    noResults: No items found
    loading: Loading items...
    itemsPerPage: Per page
    itemsPerPageAll: All
    name: Name
    amount: Amount
    serving: Serving
    itemType: Type
    calories: Calories
    carbs: Carbs (g)
    protein: Protein (g)
    fat: Fat (g)
    filters:
      title: Filters
      showFoods: Show food
      showRecipes: Show recipes

  dietTableFilters:
    search: Search

  foodModal:
    title:
      new: New food
      edit: Edit food
      view: View food
    form:
      name: Name
      description: Description
      calories: Calories
      carbs: Carbs (g)
      protein: Protein (g)
      fat: Fat (g)
      serving:
        unit: Serving unit
        value: Serving value
    errors:
      name:
        required: Name is required
      server:
        unknown: Unknown error occurred

  recipeModal:
    title:
      new: New recipe
      edit: Edit recipe
      view: View recipe
    form:
      name: Name
      description: Description
      serving:
        unit: Serving unit
        value: Serving value
    onlyShowSelected: Only show selected
    ingredientSelector: Select ingredients
    general: General
    ingredients: Ingredients
    summary: Nutrients
    noIngredients: Add ingredients to see the nutrient breakdown
    errors:
      name:
        required: Name is required
      server:
        unknown: Unknown error occurred

widgets:
  nutrientSummary:
    title: Nutrient summary
    date: Date
    noItems: No items added for today. To show the nutrient summary, {0}
    noItemsLink: add items to this day.
  healthTrend:
    title: Health trend
    date: Date of week
    noItems: No items added for today. To show the nutrient summary, {0}
    noItemsLink: add items to this day.
    trendTypes: Trend type
    trendTypeOptions:
      macros: Macros
      calories: Calories

views:
  dashboard:
    title: Health Dashboard

  diet:
    title: Food & Recipes
    search: Search
    newFoodButton: Create food
    newRecipeButton: Create recipe
    showFoods: Show food
    showRecipes: Show recipes
    notifications:
      food:
        saved: Food successfully saved
        removed: Food successfully deleted
      recipe:
        saved: Recipe successfully saved
        removed: Recipe successfully deleted

  diary:
    title: Diary
    datePicker: Date
    summary: Summary
    consumption: Consumption
    nutrientSummary: Nutrient summary
    noItems: Add items to display the nutrient breakdown
    notifications:
      saved: Diary item successfully saved
      unknownError: Unknown error occurred
