PORT: 8080
BASE_URL: http://localhost:8080/
REGISTRATION_DISABLED: false
DEFAULT_LOCALE: en

SERVICES:
  auth: http://localhost:8070/

LOGS_LABEL: awa
LOGS_CLEAN_FOLDER: true
LOGS_TO_FILE: true
LOGS_FOLDER_ABSOLUTE_PATH: null

DEV_CLIENT_PORT: 8090
DEV_API_RESPONSE_DELAY: 0

TEST_BASE_URL: null
