ABBREVIATION: awa
PORT: 8080
REGISTRATION_DISABLED: false
DEFAULT_LOCALE: en
API_URL: http://localhost:8070/

LOGS_CLEAN_FOLDER: true
LOGS_TO_FILE: false
LOGS_FOLDER_ABSOLUTE_PATH: null

DEV_CLIENT_PORT: 3000
DEV_API_RESPONSE_DELAY: 0
