PORT: 8080
BASE_URL: http://localhost:8080/
MONGO_URI: null
REGISTRATION_DISABLED: false

AUTH_ACCESS_TOKEN_EXPIRATION: 5m
AUTH_REFRESH_TOKEN_EXPIRATION: 7d
AUTH_SALT_ROUNDS: 1
AUTH_SECRET: secret123

LOGS_CLEAN_FOLDER: true
LOGS_TO_FILE: true
LOGS_FOLDER_ABSOLUTE_PATH: null

DEV_CLIENT_PORT: 8090
DEV_API_RESPONSE_DELAY: 0
